name: Deploy on OP server

on:
  push:
    branches:
      - server-op
    paths-ignore:
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: server-op

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execution permission for gradlew
        run: |
          cd backend/dominicanAppBackend
          chmod +x gradlew

      - name: Build and test with Gradle
        run: |
          cd backend/dominicanAppBackend
          ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: server-op

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_OP }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_OP_IP }} >> ~/.ssh/known_hosts

      - name: Determine new version number
        id: version
        run: |
          LAST_VERSION=$(ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "find ~/studentat/deploys -maxdepth 1 -type d -regextype posix-extended -regex '.*/[0-9]+' | sed 's#.*/##' | sort -n | tail -n1")
          if [ -z "$LAST_VERSION" ]; then
            LAST_VERSION=0
          fi
          VERSION=$((LAST_VERSION + 1))
          echo "New version is: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Debug server environment
        run: |
          ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "echo 'Current directory:'; pwd; echo 'Listing:'; ls -la; echo 'Listing ~/studentat:'; ls -la ~/studentat; echo 'Listing ~/studentat/deploys:'; ls -la ~/studentat/deploys"


      - name: Create deploy directory on server
        run: |
          ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "mkdir -p ~/studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main"

      - name: Copy repository to server
        run: |
          rsync -avz --delete --exclude '.github' ./ ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }}:~/studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main

      - name: Create .env file from template and inject secrets
        run: |
          ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "cd ~/studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main && \
          cp .env.template .env && \
          sed -i 's|http://localhost|${{ secrets.NGINX_URL_OP }}|g' .env && \
          sed -i 's/your-google-client-id/${{ secrets.GOOGLE_CLIENT_ID_OP }}/g' .env && \
          sed -i 's/your-google-client-secret/${{ secrets.GOOGLE_CLIENT_SECRET_OP }}/g' .env"

      - name: Copy migration file from previous version
        run: |
          ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "cp ~/studentat/resources/migrations/V2__Insert_init_data.sql ~/studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main/backend/dominicanAppBackend/src/main/resources/db/migration/"

      - name: Copy certbot folder from previous version
        run: |
          if [ "$VERSION" -gt 1 ]; then
            PREV_VERSION=$((VERSION - 1))
            echo "Copying certbot folder from version $PREV_VERSION to version $VERSION"
            ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "sudo cp -r ~/studentat/deploys/${PREV_VERSION}/Dominican-studentate-system-main/certbot ~/studentat/deploys/${VERSION}/Dominican-studentate-system-main/"
          else
            echo "No previous version found, skipping certbot folder copy."
          fi

      - name: Run deploy_new_version.sh on server
        run: |
          ssh ${{ secrets.SERVER_OP_USER }}@${{ secrets.SERVER_OP_IP }} "cd ~/studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main && chmod +x deploy_new_version.sh && ./deploy_new_version.sh"
