name: Deploy to OVH - Server Branch

on:
  push:
    branches:
      - server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.OVH_IP }} >> ~/.ssh/known_hosts

      - name: Determine new version number
        id: version
        run: |
          LAST_VERSION=$(ssh ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} "find /studentat/deploys -maxdepth 1 -type d -regextype posix-extended -regex '.*/[0-9]+' | sed 's#.*/##' | sort -n | tail -n1")
          if [ -z "$LAST_VERSION" ]; then
            LAST_VERSION=0
          fi
          VERSION=$((LAST_VERSION + 1))
          echo "New version is: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create deploy directory on server
        run: |
          ssh ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} "mkdir -p /studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main"

      - name: Copy repository to server
        run: |
          rsync -avz --delete --exclude '.github' ./ ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }}:/studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main

      - name: Create .env file from template and inject secrets
        run: |
          ssh ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} "cd /studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main && \
          cp .env.template .env && \
          sed -i 's|http://localhost|${{ secrets.NGINX_URL }}|g' .env && \
          sed -i 's/your-google-client-id/${{ secrets.GOOGLE_CLIENT_ID }}/g' .env && \
          sed -i 's/your-google-client-secret/${{ secrets.GOOGLE_CLIENT_SECRET }}/g' .env"

      - name: Copy migration file from previous version
        run: |
          ssh ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} "cp /studentat/resurces/migrations/V2__Insert_init_data.sql /studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main/backend/dominicanAppBackend/src/main/resources/db/migration/"

      - name: Run deploy_new_version.sh on server
        run: |
          ssh ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} "cd /studentat/deploys/${{ env.VERSION }}/Dominican-studentate-system-main && chmod +x deploy_new_version.sh && ./deploy_new_version.sh"
